project: drp
run: basemethod

dataset:
  type: "Drp3dDatasetConfig"
  path: "/work/lecomtje/Repositories/mixsim3d_gretsi/data/dataset"
  db: "/work/lecomtje/Repositories/iapy/rockai/data/dataset_random.db"
  dim: 4
  batch_size: 64
  num_workers: 2
  stats:
    - variable: "global"
      stats:
        - 32928.34934854074
        - 6935.238201002077
        - 0.
        - 64000.
    - variable: "permeability"
      stats:
        - 0
        - 6935.238201002077
        - 0.2
        - 23.
  

 
model:
  provider: "RockaiProvider"


metrics:
  names: ['r2', 'rms']
 
  
training:
  learning_rate: 1e-4
  loss: "mse"
  optimizer: "adam"
  scheduler: "step"
  epochs: 2

