project: drp
run: basemethod

dataset:
  type: "drp3d_sqlite"
  path: "/work/lecomtje/Repositories/mixsim3d_gretsi/data/dataset"
  db: "/work/lecomtje/Repositories/iapy/iapy_drp/tests/dataset_random.db"
  dim: 32
  batch_size: 16
  num_workers: 2
  mean: 32928.34934854074
  std: 6935.238201002077

 
model:
  model: "resnet18"


metrics:
  names: ['r2', 'rms']
 
  
training:
  learning_rate: 1e-4
  loss: "mse"
  optimizer: "adam"
  scheduler: "step"
  epochs: 2

